### ISSUE TITLE
possible bug - feeds not detected

### ISSUE THREAD

**Issue by atomGit** [igorlogius/list-feeds#35] opened 2023-03-17 21:19 UTC
**Describe the bug**
feeds are no longer detected on any website, including a typical wordpress site where i know rss is enabled

**Desktop (please complete the following information):**
LF v1.15.28/.29
firefox v111
linux

**Additional context**
LF stopped working fairly recently, probably within the last several weeks, but i'm not sure at which version - i think it stopped working for some sites at first, then apparently all, but i'm not sure about this

when creating a fresh profile it works, however it's not working on my default profile so i did some trouble shooting but couldn't find the problem...

* disabled all add-ons 
* started with an empty prefs.js
* re-imported the JSON file
* removed all rules from the imported JSON
* enable/disable LF

i'm not seeing anything related to LF in the browser console

**Comment by igorlogius** [comment] 2023-03-18 07:59
strange ... everything seems to be working for me 

I did delay the feed detection to counter a github login bug, but that should only make add a couple of seconds to the detection.

**Comment by igorlogius** [comment] 2023-03-18 20:12
@atomGit 
Please share a site with me, so i can directly compare my results with yours.

**Comment by atomGit** [comment] 2023-03-18 20:24
here the feed is detected: https://www.youtube.com/@Kabab/videos 

here it isn't (WordPress): https://www.corbettreport.com/

same here (WordPress): https://12bytes.org/

and here: https://21stcenturywire.com/

**Comment by atomGit** [comment] 2023-03-18 20:25
i haven't gotten around to troubleshooting further, but i'm sure i'll be able to narrow it down once i do

**Comment by atomGit** [comment] 2023-03-18 20:29
wait a minute - the feed **is** detected for corbettreport, but it takes ~13 seconds on his [contact page](https://www.corbettreport.com/contact/) which is a simple page

**Comment by igorlogius** [comment] 2023-03-18 20:35
yeah, ok ... the inital delay of 10 seconds ... might have been a bit to much ... i guess i wanted to make sure that the github bug did not cause anyone any real trouble ... at least until i could find a better solution for it. 

But i guess ... i can try turning it down to 5 seconds and see if that is still fine.

**Comment by igorlogius** [comment] 2023-03-18 20:46
To maybe clue you in a bit ... the githubs login page prevents javascript executions ... 
now ... the issue is ... that when the list-feeds injects it detection ... this doenst just trigger a error ... the login actually seems to detect and react to this injection attempt and this causes the login to fail. 

I assume that their might be other sites beside github that could protect their logins like this ... and i feared that people might be unable to log into their accounts knowing what the actual cause behind this is. 

That was also a reason, why i picked a rather generous  inital delay.

**Comment by atomGit** [comment] 2023-03-18 21:08
i personally prefer auto-feed detection, but maybe it'd be wiser to go back to manual where the user would need to click the toolbar button??? or eliminate the delay and keep an internal blacklist for long-on urls maybe - many could probably be covered with a RegEx

**Comment by igorlogius** [comment] 2023-03-18 21:31
Yeah, i am still unsure about what to do here myself.

I guess i have to check if other userscript managers are falling flat on the same issue. 
And if so ... i it might be worth raising a bug or creating a feature request ... since i personally believe that addons should have the capacitiy to overwrite such script projections since othewise users might not have the power to customize their userexperience in a way they seem fit.

**Comment by igorlogius** [comment] 2023-03-22 14:12
I most generic solution seemed to me to detect to try and detect when a page prevents a script execution ... which might lead to the error. 

Sadly i found out, that the CSP could not only be set via a HTTP header ... but also via a <meta> tag (ref. https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) 

i kind of hope that the <meta> case isn't something many websites use ... so i'll be ignoring it for now :-)

**Comment by igorlogius** [comment] 2023-03-22 15:24
well .. damn it!  Seems like firefox has a bug ... which prevents we from getting the tabId inside the webRequest.onCompleted handler ... it should normally be availabe inside the details object ... but it almost always seems to be -1 ... which indicates no tab association ... which is plain false. 

... guess this makes this issue blocked until this has been fixed.

**Comment by atomGit** [comment] 2023-03-22 16:08
> I most generic solution seemed to me to detect to try and detect when a page prevents a script execution ... which might lead to the error.

> Sadly i found out, that the CSP could not only be set via a HTTP header ... but also via a tag

i disable scripts globally by default, then allow as necessary, however on my site (WP) JS is enabled and CSP is set in .htaccess, but i commented out the CSP header and the result is the same - feed is not detected

also on corbettreport.com, where the feed [was detected](https://github.com/igorlogius/list-feeds/issues/35#issuecomment-1474984887), it isn't anymore

i think there might be something else going on besides a FF bug because LF seems to work ok if i spin up a new profile - i'm going to work on that right now and see if i can isolate something

**Comment by igorlogius** [comment] 2023-03-22 16:42
yeah, i am making a lot of mistakes at the moment ... i'll take a break and see if i can fix or revert this tomorrow.

**Comment by atomGit** [comment] 2023-03-22 16:46
beats me ... i did a bunch of testing and i couldn't isolate the cause - very weird that spinning up a fresh profile and installing LF seems to always work, but then i start overwriting the new files with small batches of my backup files and at some point LF stops working... so i delete those files and repeat the process, 1 file at a time, and i cannot reproduce it

**Comment by atomGit** [comment] 2023-03-22 18:52
"complex" is one word that could be used to describe the "modern web" - another is a "shit-hole"

avoiding auto-injection is actually better privacy wise, so i personally have no problem with having to push a button, as it were

that said, there are other feed detectors around that i believe do it automatically - i don't know if they do something different or face the same problem however - maybe you can peek at their code - feedbro and smart reader (aka smart rss) come to mind - both are feed readers that can detect feeds

**Comment by igorlogius** [comment] 2023-03-22 19:20
I thought of one other idea ... to maybe curicument this issue entirely. 

i will try to move everything the custom-feed-detection creation and the url detection into the background script. 

The content-script should then "only" be used to collect the potential urls and push feed (pun intended) them to the background process, which determines if they could be potential feeds or not. 

I am not sure if that will work, since i never tried to use dynamic code interpretation with eval inside of this scope. 

When it does work, i have hope, to have found a solution to the whole problem ... and when not ... then i might just give up on this addon entirely.

**Comment by igorlogius** [comment] 2023-03-22 22:15
@atomGit 

`1.15.35` ... might fix everything.  

Remember to replace the `custum-feed-detection.json` with the new one in the repo, since the format changed slightly. 

Please let me know if you find any issues.

**Comment by atomGit** [comment] 2023-03-22 22:43
hot damn - it detects the feed on my site (WP) with or without JS

i tested a couple other places and it's working there as well

from what you said earlier it seems like you made a major change to the way feeds are detected - that being the case, is the delay still necessary?  it's not as long as it was though - seems to kick in ~2 seconds after page load

**Comment by igorlogius** [comment] 2023-03-22 23:58
> is the delay still necessary

i can remove the delay and we can see if that causes any issues

**Comment by igorlogius** [comment] 2023-03-23 00:57
Ok, i'll close this issue now ... because it is all over the place. 

The main problem should be solved at least for now.

**Closed by igorlogius** 2023-03-23 00:57 UTC
Labels: Bug
